services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/payment_app?authSource=admin
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  mongodb_data: